// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qghjgcpwtfgexcmfapmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnaGpnY3B3dGZnZXhjbWZhcG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjIyNzIsImV4cCI6MjA1NzQzODI3Mn0.4NS-M4Ygneb6T4Dt5JQ79iGGHIZ0Q4GD8jUzXlG6kjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);